
% This file is automatically generated.
function x = test()
    x = functiontests(localfunctions());
end

function test__typo__edited(t)
    X = 'README.md';
   
    path_to_original = pex.path.to_system_path('#+pex/+task/+typo/README.md');
    path_to_current = pex.path.to_system_path(fullfile(pex.task.typo.path, X));
 
    function initialize()
        copyfile(path_to_original, X, 'f');
    end

    if exist(path_to_current, 'file') == 0
        initialize();
    end

    original = pex.trim_file(path_to_original);
    correct = strrep(original, 'MALTAB', 'MATLAB');
    current = pex.trim_file(path_to_current);

    ok = strcmp(current, original) || strcmp(current, correct);
    if ~ok
        verifyTrue(t, ok, sprintf('You edited %s, but it is not the original value or the correct value. It will be re-initialized.', X));
        initialize();
        return
    end

    verifyTrue(t, strcmp(current, correct), sprintf('You must edit %s.', X));
end

